server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: true  # 不向eureka server 注册自己
    fetch-registry: false
    service-url:   #  eureka server 的地址， 咱们单实例模式就写自己好了
      defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
