server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/idm_server_jiaogx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: jgx246580
  cloud:
    consul:
      host: 192.168.5.105
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true


