server:
  port: 8004

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/idm_server_jiaogx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: jgx246580
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 192.168.5.105:2181
