server:
  port: 80
spring:
  application:
    name: cloud-consumeropenfeign-order
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    # 显示实例名称
    instance-id: order80
    # 显示ip
    prefer-ip-address: true

feign:
  client:
    config:
      default: #这里就是指的所有被加载的默认FeignClient实现的服务配置都生效
        connectTimeout: 5000
        readTimeout: 5000
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.openfeigntest.springcloud.service.PaymentService: debug